settings:
  database: # database to save player data
    auth: # database's auth info. only required if save-method is mysql
      url: 'jdbc:mysql://localhost:3306/economy?createDatabaseIfNotExist=true'
      username: 'root'
      password: ''
  logging: # logs all transactions
    enabled: true # true, false
    format: "%s sent %a %c to %t" # %s - sender, %a - amount, %c - currency, %t - target
  bal-top: # balance-top update settings
    interval: 60

currency:
  singular-name: 'dollar'
  plural-name: 'dollars'
  separator: '.'
  display-format: '%balance% %currencyname%'
  max-amount: 10000000000000000
  initial-amount: 5000.00
  transactions: true
  tax:
    all: 0
    transactions: 10
  format-balance:
    1000: 'k'
    1000000: 'm'

